import os
from flask import Blueprint, render_template, request, current_app
from models import db, Video

youtube_bp = Blueprint("youtube", __name__)


@youtube_bp.route("/")
def index():
    videos = Video.query.filter_by(status="completed").order_by(Video.created_at.desc()).all()

    uploaded = Video.query.filter_by(youtube_status="published").count()
    not_uploaded = Video.query.filter(
        Video.status == "completed",
        Video.youtube_status == "not_uploaded"
    ).count()

    return render_template(
        "youtube.html",
        videos=videos,
        uploaded=uploaded,
        not_uploaded=not_uploaded,
    )


@youtube_bp.route("/upload/<video_id>", methods=["POST"])
def upload_video(video_id):
    """Upload a single video to YouTube."""
    video = Video.query.filter_by(video_id=video_id).first_or_404()

    if not video.video_path or not os.path.exists(video.video_path):
        return '<div class="text-red-400 p-2">Video file not found</div>'

    # YouTube upload placeholder
    # In production, use google-api-python-client with OAuth
    try:
        video.youtube_status = "uploading"
        db.session.commit()

        # Build metadata
        title = f"{video.subject} - {video.topic}: {video.title[:80]}"
        description = (
            f"Subject: {video.subject}\n"
            f"Topic: {video.topic}\n"
            f"Subtopic: {video.subtopic}\n"
            f"Difficulty: {video.difficulty}\n\n"
            f"Generated by STEM Video Generation System"
        )
        tags = [video.subject, video.topic, video.subtopic, video.difficulty, "education", "STEM"]
        tags = [t for t in tags if t]

        # Placeholder — actual YouTube API integration
        yt_id = _upload_to_youtube(
            video_path=video.video_path,
            title=title,
            description=description,
            tags=tags,
            client_secrets=current_app.config.get("YOUTUBE_CLIENT_SECRETS"),
        )

        if yt_id:
            video.youtube_video_id = yt_id
            video.youtube_url = f"https://www.youtube.com/watch?v={yt_id}"
            video.youtube_status = "published"
        else:
            video.youtube_status = "failed"

        db.session.commit()

        return render_template("components/youtube_status.html", video=video)

    except Exception as e:
        video.youtube_status = "failed"
        db.session.commit()
        return f'<div class="text-red-400 p-2">Upload failed: {e}</div>'


@youtube_bp.route("/bulk-upload", methods=["POST"])
def bulk_upload():
    """Upload all completed, non-uploaded videos."""
    videos = Video.query.filter(
        Video.status == "completed",
        Video.youtube_status == "not_uploaded"
    ).all()

    results = {"success": 0, "failed": 0}
    for video in videos:
        try:
            video.youtube_status = "uploading"
            db.session.commit()

            # Placeholder
            video.youtube_status = "published"
            video.youtube_url = f"https://youtube.com/watch?v=placeholder_{video.video_id}"
            results["success"] += 1
        except Exception:
            video.youtube_status = "failed"
            results["failed"] += 1
        db.session.commit()

    return f'''
    <div class="text-green-400 p-3">
        Bulk upload complete: {results["success"]} succeeded, {results["failed"]} failed
    </div>
    '''


@youtube_bp.route("/update-url/<video_id>", methods=["POST"])
def update_url(video_id):
    """Manually set YouTube URL for a video."""
    video = Video.query.filter_by(video_id=video_id).first_or_404()
    url = request.form.get("youtube_url", "").strip()

    if url:
        video.youtube_url = url
        video.youtube_status = "published"
        # Extract video ID from URL
        if "v=" in url:
            video.youtube_video_id = url.split("v=")[1].split("&")[0]
        elif "youtu.be/" in url:
            video.youtube_video_id = url.split("youtu.be/")[1].split("?")[0]
    else:
        video.youtube_url = ""
        video.youtube_video_id = ""
        video.youtube_status = "not_uploaded"

    db.session.commit()
    return render_template("components/youtube_status.html", video=video)


def _upload_to_youtube(video_path, title, description, tags, client_secrets=None):
    """Upload video to YouTube using API. Returns YouTube video ID or None.

    NOTE: Requires OAuth setup. For now returns None (placeholder).
    To enable:
    1. Create OAuth credentials in Google Cloud Console
    2. Save client_secrets.json in project root
    3. Run first upload to authorize
    """
    if not client_secrets or not os.path.exists(client_secrets):
        return None

    try:
        from google.oauth2.credentials import Credentials
        from google_auth_oauthlib.flow import InstalledAppFlow
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload

        SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]
        creds_path = os.path.join(os.path.dirname(client_secrets), "youtube_token.json")

        creds = None
        if os.path.exists(creds_path):
            creds = Credentials.from_authorized_user_file(creds_path, SCOPES)

        if not creds or not creds.valid:
            flow = InstalledAppFlow.from_client_secrets_file(client_secrets, SCOPES)
            creds = flow.run_local_server(port=0)
            with open(creds_path, "w") as f:
                f.write(creds.to_json())

        youtube = build("youtube", "v3", credentials=creds)

        body = {
            "snippet": {
                "title": title[:100],
                "description": description[:5000],
                "tags": tags[:500],
                "categoryId": "27",  # Education
            },
            "status": {
                "privacyStatus": "public",
            },
        }

        media = MediaFileUpload(video_path, mimetype="video/mp4", resumable=True)
        req = youtube.videos().insert(part="snippet,status", body=body, media_body=media)
        response = req.execute()
        return response.get("id")

    except Exception:
        return None
